/** Required, always-visible reminder that nothing here is financial advice. */
export default function Disclaimer({ compact = false }) {
  if (compact) {
    return (
      <p className="disclaimer compact">
        ⚠️ Not financial advice. Signals are educational and may use mock data.
      </p>
    );
  }
  return (
    <div className="disclaimer">
      <strong>Not financial advice.</strong> Market Monitor is an educational demo. Suggestions
      are generated by simple, automated technical rules and may be based on delayed or mock
      data. Virtual portfolios use play money — no real trades are ever placed. Do your own
      research before making any investment decision.
    </div>
  );
}
